version: "3.3"

networks:
    inception:

volumes:
    wordpress:
        driver: local
        driver_opts:
            o: bind
            type: none
            device: /home/adelille/data/wordpress
    database:
        driver: local
        driver_opts:
            o: bind
            type: none
            device: /home/adelille/data/database

services:
# https://hub.docker.com/_/nginx
    nginx:
        container_name: nginx
        build: ./requirements/nginx
        image: nginx:nginx
        depends_on:
            - wordpress
        restart: always
        networks:
            - inception
        ports:
            - "8080:443"
            - "443:443"
        volumes:
#            - /home/adelille/data/wordpress:/var/www/wordpress
            - wordpress:/var/www/wordpress

    wordpress:
        container_name: wordpress
        build: ./requirements/wordpress
        image: wordpress:wordpress
        depends_on:
            - mariadb
        restart: always
        networks:
            - inception
        ports:
            - "9000:9000"
        volumes:
#            - /home/adelille/data/wordpress:/var/www/wordpress
            - wordpress:/var/www/wordpress
        env_file:
            - "./.env"

    mariadb:
        container_name: mariadb
        build: ./requirements/mariadb
        image: mariadb:mariadb
        restart: always
        networks:
            - inception
        volumes:
#            - /home/adelille/data/database:/var/lib/mysql
            - database:/var/lib/mysql
        env_file:
            - "./.env"
